version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "mvpete"
    assignees:
      - "mvpete"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    ignore:
      # Ignore major version updates for these packages to avoid breaking changes
      - dependency-name: "Microsoft.CodeAnalysis.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Mono.Cecil"
        update-types: ["version-update:semver-major"]
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "mvpete"
    assignees:
      - "mvpete"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"