name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    name: 'Auto-merge Dependabot PRs'
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Configure NuGet
      run: |
        echo "Using NuGet.config for package source configuration"
      env:
        NUGET_CERT_REVOCATION_MODE: offline
        DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0
    
    - name: Restore and build
      run: |
        dotnet restore Aspekt.sln --verbosity normal
        dotnet restore Aspekt.Bootstrap.Tasks/Aspekt.Bootstrap.Tasks.csproj --verbosity normal
        dotnet build Aspekt.sln --configuration Release
    
    - name: Run tests
      continue-on-error: true
      run: |
        dotnet test Aspekt.sln --configuration Release --no-build --verbosity minimal
    
    - name: Enable auto-merge for Dependabot PRs
      if: success()
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}