name: Documentation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    paths:
      - 'docs/**'
      - '*.md'
      - '.github/workflows/docs.yml'

jobs:
  update-toc:
    name: 'Update Table of Contents'
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate TOC for documentation files
      run: |
        # Install markdown-toc if needed
        npm install -g markdown-toc
        
        # Update TOC in main documentation files
        for file in docs/*.md; do
          if [[ -f "$file" ]]; then
            echo "Updating TOC for $file"
            markdown-toc -i "$file"
          fi
        done
    
    - name: Commit TOC updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if git diff --quiet; then
          echo "No TOC changes to commit"
        else
          git add docs/*.md
          git commit -m "docs: auto-update table of contents [skip ci]"
          git push
        fi