name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  create-release:
    name: 'Create GitHub Release'
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Configure NuGet
      run: |
        dotnet nuget config set signatureValidationMode accept
        dotnet nuget config set packagePathResolve true
    
    - name: Restore dependencies
      run: dotnet restore Aspekt.sln
    
    - name: Build solution
      run: dotnet build Aspekt.sln --configuration Release --no-restore
    
    - name: Run tests
      run: |
        dotnet test Aspekt.Test/Aspekt.Test.csproj --configuration Release --no-build
        dotnet test Aspekt.Bootstrap.Test/Aspekt.Bootstrap.Test.csproj --configuration Release --no-build
        dotnet test Aspekt.Foundation.Test/Aspekt.Foundation.Test.csproj --configuration Release --no-build
        dotnet test Aspekt.Logging.Test/Aspekt.Logging.Test.csproj --configuration Release --no-build
    
    - name: Create NuGet packages
      run: |
        dotnet pack Aspekt/Aspekt.csproj --configuration Release --no-build --output nupkgs
        dotnet pack Aspekt.Contracts/Aspekt.Contracts.csproj --configuration Release --no-build --output nupkgs
        dotnet pack Aspekt.Logging/Aspekt.Logging.csproj --configuration Release --no-build --output nupkgs
    
    - name: Generate release notes
      id: release_notes
      run: |
        $tag = "${{ github.ref_name }}"
        $version = $tag -replace '^v', ''
        
        $releaseNotes = "# Aspekt $version - AI Era Release`n`n"
        $releaseNotes += "## Welcome to the AI Era of Aspekt!`n`n"
        $releaseNotes += "This major release represents a complete modernization and enhancement of the Aspekt AOP framework, developed with AI assistance to ensure comprehensive coverage, best practices, and production-ready quality.`n`n"
        $releaseNotes += "## What's New in v3.0.0`n`n"
        $releaseNotes += "- **AI-Enhanced Development**: Complete codebase review and enhancement`n"
        $releaseNotes += "- **Modern .NET Support**: Full compatibility with .NET 6.0, 8.0, and 9.0`n"
        $releaseNotes += "- **Advanced Async Support**: Comprehensive ValueTask patterns and cancellation token support`n"
        $releaseNotes += "- **Production-Ready Contracts**: Complete Design by Contract implementation`n"
        $releaseNotes += "- **Enhanced IL Weaving**: Improved Mono.Cecil integration with better error handling`n"
        $releaseNotes += "- **Comprehensive Documentation**: AI-curated examples, guides, and best practices`n"
        $releaseNotes += "- **Professional CI/CD**: Multi-version testing, security scanning, and automated releases`n"
        $releaseNotes += "- **Return Value Interception**: Advanced IAspectExitHandler capabilities`n"
        $releaseNotes += "- **Thread Safety**: Enhanced concurrent execution support`n`n"
        $releaseNotes += "## Package Information`n`n"
        $releaseNotes += "This release includes the following NuGet packages:`n`n"
        $releaseNotes += "- **Aspekt** - Core AOP functionality`n"
        $releaseNotes += "- **Aspekt.Contracts** - Design by Contract support`n"
        $releaseNotes += "- **Aspekt.Logging** - Built-in logging aspects`n`n"
        $releaseNotes += "## Installation`n`n"
        $releaseNotes += "Install core package: Install-Package Aspekt -Version $version`n"
        $releaseNotes += "Install contracts: Install-Package Aspekt.Contracts -Version $version`n"
        $releaseNotes += "Install logging: Install-Package Aspekt.Logging -Version $version`n`n"
        $releaseNotes += "## Documentation`n`n"
        $releaseNotes += "- Getting Started Guide: https://github.com/mvpete/aspekt/blob/master/docs/GETTING_STARTED.md`n"
        $releaseNotes += "- API Reference: https://github.com/mvpete/aspekt/blob/master/docs/API.md`n"
        $releaseNotes += "- Examples: https://github.com/mvpete/aspekt/blob/master/docs/EXAMPLES.md`n"
        $releaseNotes += "- Troubleshooting: https://github.com/mvpete/aspekt/blob/master/docs/TROUBLESHOOTING.md`n`n"
        $releaseNotes += "## Requirements`n`n"
        $releaseNotes += "- .NET 6.0 or later`n"
        $releaseNotes += "- Visual Studio 2022 or VS Code`n"
        $releaseNotes += "- MSBuild 17.0+`n"
        
        # Save to file for GitHub release
        $releaseNotes | Out-File -FilePath release-notes.md -Encoding utf8
        
        # Set output for next step
        echo "version=$version" >> $env:GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: 'Aspekt v${{ steps.release_notes.outputs.version }}'
        body_path: release-notes.md
        files: |
          nupkgs/*.nupkg
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}